"""Added role and created_at to User model

Revision ID: 119cd6da6ca0
Revises: 
Create Date: 2025-02-08 16:46:23.728692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119cd6da6ca0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('user', 'admin', name='user_roles'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('user', 'admin', name='user_roles'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
