"""Upgraded time to integer

Revision ID: 5da842e78f9f
Revises: e0fe67bc3e83
Create Date: 2025-02-13 23:23:46.123476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5da842e78f9f'
down_revision = 'e0fe67bc3e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['question_statement'])

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('time_duration',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('time_duration',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
